version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: pgvector-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: exidhani11
      POSTGRES_DB: pgvector_demo
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'shared_preload_libraries=vector'

volumes:
  pgdata:
